// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFuG4W1fovPyl9Y19WoBotL4y22fuHfWU',
    appId: '1:654053890266:web:e11c13e9b1f291dffcede3',
    messagingSenderId: '654053890266',
    projectId: 'video-games-manager',
    authDomain: 'video-games-manager.firebaseapp.com',
    storageBucket: 'video-games-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-zG7AAS2qRLUIca9zKhCMiq1wosHjPpY',
    appId: '1:654053890266:android:3f733d8f700ba1e9fcede3',
    messagingSenderId: '654053890266',
    projectId: 'video-games-manager',
    storageBucket: 'video-games-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZque8BN5JMpnp5Nu_s9iEHtc88qInPE',
    appId: '1:654053890266:ios:4d6251210b9c092afcede3',
    messagingSenderId: '654053890266',
    projectId: 'video-games-manager',
    storageBucket: 'video-games-manager.firebasestorage.app',
    androidClientId: '654053890266-08n1emp2dksc8t38nduacbv053vjqf77.apps.googleusercontent.com',
    iosClientId: '654053890266-qoelac6v8fkclhc0br4pu5ejfnbv0oaj.apps.googleusercontent.com',
    iosBundleId: 'fr.alex.eloi.videoGamesManagerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDZque8BN5JMpnp5Nu_s9iEHtc88qInPE',
    appId: '1:654053890266:ios:4d6251210b9c092afcede3',
    messagingSenderId: '654053890266',
    projectId: 'video-games-manager',
    storageBucket: 'video-games-manager.firebasestorage.app',
    androidClientId: '654053890266-08n1emp2dksc8t38nduacbv053vjqf77.apps.googleusercontent.com',
    iosClientId: '654053890266-qoelac6v8fkclhc0br4pu5ejfnbv0oaj.apps.googleusercontent.com',
    iosBundleId: 'fr.alex.eloi.videoGamesManagerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFuG4W1fovPyl9Y19WoBotL4y22fuHfWU',
    appId: '1:654053890266:web:eddcdad854a62243fcede3',
    messagingSenderId: '654053890266',
    projectId: 'video-games-manager',
    authDomain: 'video-games-manager.firebaseapp.com',
    storageBucket: 'video-games-manager.firebasestorage.app',
  );

}